service: metigy
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

functions:
  get_info:
    handler: app.handler.get_or_create
    events:
      - http:
          method: post
